# Generated by Django 3.1 on 2020-08-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mal_id', models.IntegerField()),
                ('title', models.TextField()),
                ('cover', models.TextField()),
                ('year', models.IntegerField()),
                ('season', models.TextField()),
                ('themes', models.JSONField()),
            ],
        ),
    ]
