# Generated by Django 3.1 on 2020-08-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.JSONField(),
        ),
    ]
