# Generated by Django 3.1 on 2020-08-20 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20200820_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='themes',
        ),
    ]
