# Generated by Django 3.1 on 2020-08-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20200820_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.CharField(max_length=20),
        ),
    ]
