# Generated by Django 3.1 on 2020-08-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_auto_20200820_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mal_id', models.IntegerField()),
                ('theme_id', models.IntegerField(unique=True)),
                ('artist_id', models.IntegerField(blank=True)),
                ('title', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('episodes', models.TextField(blank=True, default='')),
                ('views', models.IntegerField(default=0)),
                ('mirrors', models.JSONField()),
            ],
        ),
    ]
