# Generated by Django 3.1 on 2020-08-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='episodes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
