# Generated by Django 3.1 on 2020-08-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_auto_20200820_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
