# Generated by Django 3.1 on 2020-08-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_theme_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme_id',
            field=models.TextField(unique=True),
        ),
    ]
