# Generated by Django 3.1 on 2020-08-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_auto_20200820_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='artist_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='theme',
            name='category',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='episodes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
