# Generated by Django 3.1 on 2020-08-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_auto_20200820_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mal_id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('cover', models.TextField()),
                ('themes', models.JSONField()),
            ],
        ),
    ]
