# Generated by Django 3.1 on 2020-08-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='cover',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='cover',
            field=models.TextField(default=''),
        ),
    ]
